version: "3"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    # privileged: true
    # devices:
      # - "/dev/kmsg"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - grafana
    depends_on:
      - cadvisor

